# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCloedH2cCZVfaF3sQyjOt6w0Fg60va6
"""

import pandas as pd
from pandas import Series, DataFrame

# ex.92
d = pd.read_csv("/content/ex9.2_1.csv",sep=",")
print(d.head())

print(pd.crosstab(d["gender"],d["umu"],margins=True,normalize=True))

d = pd.read_csv("/content/ex9.2_2.csv",sep=",")
print(d.head())
print(pd.crosstab(d["marrige"],d["umu"],margins=True,normalize=True))

# ex.93
d = pd.read_csv("/content/ex9.3.csv",sep=",")
print(d.head())
print(pd.crosstab(d["edu"],d["umu"],margins=True,normalize="index"))

from scipy.stats import chi2_contingency
from scipy.stats import power_divergence

# ex9.7
d = pd.read_csv("/content/ex9.2_1.csv")
cd = pd.crosstab(d["gender"],d["umu"])
stat,p,dof,expected = chi2_contingency(cd,correction=False)
print(stat)
print(p)

d = pd.read_csv("/content/ex9.2_2.csv")
cd = pd.crosstab(d["marrige"],d["umu"])
stat,p,dof,expected = chi2_contingency(cd,correction=False)
print(stat)
print(p)

# ex9.9
d = pd.read_csv("/content/ex9.2_1.csv")
cd = pd.crosstab(d["gender"],d["umu"])
stat,p,dof,expected = chi2_contingency(cd,correction=False)
print((stat/len(d))**0.5)

d = pd.read_csv("/content/ex9.2_2.csv")
cd = pd.crosstab(d["marrige"],d["umu"])
stat,p,dof,expected = chi2_contingency(cd,correction=False)
print("chisq",stat,"¥n","p-value:",p,"¥n","degree of freedom:",dof)

print((stat/len(d))**0.5)

# ex9.1
cd = [[30,17,3,3,5],[20,31,24,31,12],[2,4,11,17,40]]
stat,p,dof,expected = chi2_contingency(cd,correction=False)
print("chisq",stat,"¥n","p-value:",p,"¥n","degree of freedom:",dof)
print((stat/(len(d)*(3-1)))**0.5)



