# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbuZUqedm5BfLytX8ZE9k9Fx8wJadvFK
"""

import pandas as pd

from pandas import Series, DataFrame

d = pd.read_csv("/content/ex12.1.csv",sep=",")

print(d.head())

import statsmodels.api as sm

from statsmodels.formula.api import logit

formula = "Dwork ~ hasincome"

out = logit(formula, data=d).fit()

print(out.summary())



formula = "Dwork ~ 1"
out = logit(formula, data=d).fit()
print(out.summary)

formula = "Dwork ~ hasincome + age + Dchildren"
out = logit(formula, data=d).fit()
print(out.summary())

import math

yhat = out.params[0] + out.params[1]*d["hasincome"].mean()+out.params[2]*d["age"].mean()+out.params[3]*d["Dchildren"].mean()

phat = math.exp(yhat)/(1*math.exp(yhat))

print(phat*(1-phat)*out.params[1])
print(phat*(1-phat)*out.params[2])
print(phat*(1-phat)*out.params[3])



import math

yhat1 = out.params[0] + out.params[1]*d["hasincome"].mean()+out.params[2]*d["age"].mean()+out.params[3]*d["Dchildren"].mean()

phat1 = math.exp(yhat1)/(1+math.exp(yhat1))
yhat0 = yhat = out.params[0] + out.params[1]*d["hasincome"].mean()+out.params[2]*d["age"].mean()+out.params[3]*d["Dchildren"].mean()
phat0 = math.exp(yhat0)/(1+math.exp(yhat0))
print(phat1)
print(phat0)



import numpy as np
x = pd.DataFrame({"xd":range(0,100,2)})
print(len(x),x)
x["yhat"] = out.params[0]+out.params[1]*x["xd"] + out.params[2]*d["age"].mean()+out.params[3]*d["Dchildren"].mean()
x["phat"] = np.exp(x["yhat"])/(1+np.exp(x["yhat"]))
print(x.head())

import matplotlib.pyplot as plt

import seaborn

import sklearn

plt.plot(x["xd"],x["phat"],linestyle="solid")
plt.show()



import numpy as np
x["yhat1"] = out.params[0]+out.params[1]*x["xd"]+out.params[2]*d["age"].mean()+out.params[3]
x["phat1"] = np.exp(x["yhat1"])/(1+np.exp(x["yhat1"]))

x["yhat0"] = out.params[0] + out.params[1]*x["xd"]+out.params[2]*d["age"].mean()
x["phat0"] = np.exp(x["yhat0"])/(1+np.exp(x["yhat0"]))
print(x.head())

import matplotlib.pyplot as plt
import seaborn

plt.plot(x["xd"],x["phat0"],linestyle="solid")
plt.plot(x["xd"],x["phat1"],linestyle="solid")
plt.show()

